spring:
  application:
    name:dine-in-order-api

# DATASOURCE CONFIGURATION
  datasource:
    url:jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist:true
    username:root
    password:root
  jpa:
    show-sql:true
  hibernate:
    ddl-auto:update

